name = "ai-worker-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Cloudflare AI binding (optional)
[ai]
binding = "AI"

# Cloudflare dashboard logs (optional)
[observability]
enabled = false
head_sampling_rate = 1

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
